name: Lints, tests and builds
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipeline:
    runs-on: windows-2019
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Staring node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install modules
        run: npm install

      - name: Build production
        run: npm run build:prod

      - name: Lint typescipt
        run: npm run lint:ts
      - name: Lint scss
        run: npm run lint:scss

      - name: Unit tests
        run: npm run test:unit

      - name: Storybook build
        run: npm run storybook:build
      - name: Screenshot tests
        run: npm run test:loki:ci
