# name: Lints, tests and builds
# on:
#   push:
#     branches: [master]
#   pull_request:
#     branches: [master]
# jobs:
#   pipeline:
#     runs-on: windows-2019
#     strategy:
#       matrix:
#         node-version: [16.x]

#     steps:
#       - uses: actions/checkout@v2
#       - name: Staring node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}

#       - name: Install modules
#         run: npm install

#       - name: Build production
#         run: npm run build:prod

#       - name: Lint typescipt
#         if: always()
#         run: npm run lint:ts
#       - name: Lint scss
#         if: always()
#         run: npm run lint:scss

#       - name: Unit tests
#         if: always()
#         run: npm run test:unit

#       - name: Storybook build
#         run: npm run sb:build
#       - name: Screenshot tests
#         run: npm run test:loki:ci

name: linting, testing, building
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: 'pages'
  cancel-in-progress: true
jobs:
  build-and-ui-testing:
    runs-on: windows-2019
    concurrency: ci-${{ github.ref }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm ci
      - name: build production project
        run: npm run build:prod
        if: always()
      - name: build storybook
        run: npm run sb:build
        if: always()
      - name: screenshot testing
        run: npm run test:ui:ci
        if: always()
      - name: Generate HTML report
        run: npm run test:loki:report
        if: always()
      - name: Setup Pages
        uses: actions/configure-pages@v2
        if: always()
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        if: always()
        with:
          path: '.loki'
      - name: Deploy to GitHub Pages
        id: deployment
        if: always()
        uses: actions/deploy-pages@v1

  checks:
    runs-on: windows-2019
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm ci
      - name: linting typescript
        run: npm run lint:ts
        if: always()
      - name: linting css
        run: npm run lint:scss
      - name: unit testing
        if: always()
        run: npm run test:unit
